### PR TITLE
scc: Add -specify option to find loops in boxes

### PR DESCRIPTION
**Pull request by Ravenslofty**
Part of the fix for #2530: enhance SCC to detect logic loops through combinational specify rules.

### CODE REVIEW

**Comment by Ravenslofty** [comment]
Fixed a bug where `scc` segfaulted, since `bit.wire` may be `nullptr` if `bit` is a constant.

**Review by clairexen — APPROVED** [review]
LGTM. Any reason why this code only cares about `$specify2` and not `$specify3`?

**Comment by Ravenslofty** [comment]
I'm happy to correct this assumption if it's wrong, but my understanding is that `$specify2` describes combinational paths (e.g. `(X => Y) = N`), while `$specify3` describes synchronous paths (e.g. `(posedge CLK => (Y : X)) = N`), and it's combinational paths that we care about in this context.

**Comment by clairexen** [comment]
Well, there's `-all_cell_types` but I guess it's not relevant for the use-case.  ;)

**Pull request merged**
