### PR TITLE
Remove redundant (but also altered) rule

### PR DESCRIPTION
**Pull request by mmicko**

### CODE REVIEW

**Comment by povik** [comment]
Ha, as it happens I just posted a fix too. Anyway I think mine is the proper fix, since we still need to make sure the `techlibs/quicklogic` directory exists in the build tree at the time we are generating the header.

(Only after I learned about what `VPATH` does in Makefiles did the linked YoWASP build failure in #4045 start to make sense.)

**Comment by povik** [comment]
The other PR: #4053

**Comment by mmicko** [comment]
Agree. Already asked @whitequark to take a look at your PR.

**Comment by whitequark** [comment]
What the heck is `VPATH`.

**Comment by whitequark** [comment]
Okay, I see, that's cursed.

**Pull request closed without merging**
