### PR TITLE
Add N:* to select language, fix some old code

### PR DESCRIPTION
**Pull request by cliffordwolf**

### CODE REVIEW

**Comment by nakengelhardt** [comment]
Not sure whether to merge this now or wait for #1763...

**Comment by boqwxp** [comment]
This is subsumed within #1763 and that should (hopefully) be ready to merge now, or if not it will be very soon.  So this should probably be closed.

**Comment by nakengelhardt** [comment]
Confirmed: github is clever enough to notice that this PR was included in #1763 and automatically marks it as merged :D

**Comment by boqwxp** [comment]
Yep, cool!  TIL

**Pull request merged**
