### PR TITLE
Fix formatting for msys2 mingw build

### PR DESCRIPTION
**Pull request by mmicko**
- msys2 builds anyway can not be compiled with plugins so made config so compile work by default
- %zu is not supported in msys mingw, mxe and VisualStudio older then 2015 so made define for size_t formatting
- update places where wrong formatting have been used for size_t values
- fixed cast and not defined symbol in launcher.c

TODO: check mxe build after these changes

### CODE REVIEW

**Comment by mmicko** [comment]
Added fixes to enable MXE builds. Used https://github.com/mmicko/mxe-docker as environment

**Comment by cliffordwolf** [comment]
I think instead of `SIZE_T_FMT` we should just use `%d` and cast the `size_t` argument to `int`. That's what we do in all the other cases where we print a `size_t` (those few instances this PR touches are relatively new code).

**Comment by cliffordwolf** [comment]
Also, instead of `x.size()` one should generally use `GetSize(x)` in Yosys code anyways. That already returns an `int`. (Yes, I know we consistently use size_t for pass args, but that's just because this pattern is older than `GetSize()`.)

**Comment by cliffordwolf** [comment]
I did cherry pick 73dcf31862182a5dd5f45e684621c27f7adc5d0f into 0.9-rc now.

**Comment by mmicko** [comment]
@cliffordwolf Right, most is code that came after previous release. Will take care and convert code to use GetSize  so %d is then fine

**Comment by mmicko** [comment]
Cleaned a bit pull request. 
Last two 3f633690ae3d0c8753866d136851b8f0129cb643 and 7a65ed19a5921ff219fd208d2712e09b5e5894dd are needed for latest MXE version build. If you could send me version you have deployed just to confirm that it works without this on old one.

**Pull request merged**
