### PR TITLE
Corrected handling of nested typedefs of struct/union

### LINKED ISSUE #3555: Issue using typedef with packed struct in packed union
### Version

0.22

### On which OS did this happen?

macOS

### Reproduction Steps

Try to compile this SV code:

```
typedef struct packed {
  logic [7:0] a;
  logic [7:0] b;
} Foo;

typedef Foo Bar;

typedef union packed {
  Bar bar;
  Foo foo;
} FooBar;
```

### Expected Behavior

It should work fine. I tried it in VCS with some extra asserts and it compiles:

```
module StaticAssert;
  if ($bits(Foo) != 16)
    $error("Foo is not the right length");
  if ($bits(Bar) != 16)
    $error("Bar is not the right length");
  if ($bits(FooBar) != 16)
    $error("FooBar is not the right length");
endmodule
```

### Actual Behavior

You get this error:

    ERROR: member bar of a packed union has 1 bits, expecting 16

If you change the second `typedef` to just be a copy of the structure then it works fine.

### PR DESCRIPTION
**Pull request by daglem**
Fixes #3555

### CODE REVIEW

**Review by zachjs — CHANGES_REQUESTED** [review]
Thank you for your contribution! This change unfortunately causes a regression due to a long-standing deficiency in `copyTypeDefinition`: it substitutes blindly without awareness of scoping or shadowing.

Before this change, `blk.y` appropriately has width 5. After, the shadowing of `W` causes it to incorrectly have width 10.
```SystemVerilog
module top;
    localparam W = 5;
    typedef logic [W-1:0] T;
    T x;
    if (1) begin : blk
        localparam W = 10;
        typedef T U;
        typedef logic [W-1:0] V;
        U y;
        V z;
    end
endmodule
```

I think it's important to avoid this regression in fixing the original issue. Possible routes may involve full handling of `AST_WIRETYPE` in struct/union resolution or adding some scoping logic to `copyTypeDefinition`.

**Comment by daglem** [comment]
Oh. Thanks for reviewing and avoiding the regression!

Could you add your scoping example to the tests?

**Comment by daglem** [comment]
I *finally* got this working - countless hours spent for a small improvement.

I don't think `copyTypeDefinition` can be made to work, since IUC that would require folding of constants from within `verilog_parser.y`.

I have thus removed `copyTypedefinition` in favor of resolving struct/union types in `simplify.cc`. To make this work, it was necessary to differentiate between structs/unions within typedefs (must be expanded) and in wires (must be packed). With `copyTypeDefinition`, only the latter was needed.

**Comment by daglem** [comment]
@zachjs Could you please have a look at this again?

I just amended the commit to check for an instance in `simplify.c` in a less intrusive way - the diff is quite small now.

**Comment by clairexen** [comment]
@zachjs I don't feel knowledgeable enough about this code path to review this. Cab you have another look?

**Review by zachjs — APPROVED** [review]
This is a good step in the right direction. Thank you! I will merge this shortly _after_ the next release is cut.

**Pull request merged**
