### PR TITLE
Upstream QuickLogic k6n10f flow

### PR DESCRIPTION
**Pull request by povik**
- [x] Look into libmap-based inference not setting the right attributes for TDP36K per-configuration renaming in QuickLogic’s master
- [x] Sort out the licensing issue
- [x] create a draft PR from Martin's branch
- [x] Add the tests for the base arch cells
- [x] Add small simulation tests for memory
  - [x] for expected code patterns, check they infer
  - [x] and simulation check that they work for some selected addresses
- [x] Add small simulation tests for DSP
  - [x] for expected code patterns, check they infer
  - [x] and simulation check that they work for some selected values

### CODE REVIEW

**Comment by povik** [comment]
(I will do one final rebase with squashing of fixups when we move this PR away from draft, I want the addition of the license header be there in the commit that checked in the file.)

**Comment by povik** [comment]
Force pushed with rebase and squashing of fixup commits

**Comment by whitequark** [comment]
@povik I *think* this broke the YoWASP build: https://github.com/YoWASP/yosys/actions/runs/7094599738/job/19310141018#step:7:380

**Comment by povik** [comment]
@whitequark Let me look into it.

**Comment by povik** [comment]
@whitequark As a sidenote, what would it take to have the YoWASP build in the mainline CI?

**Comment by povik** [comment]
@mmicko Look above. Possibly something we could add to the Jenkins CI to run on the master at least, not necessarily on every PR.

**Comment by whitequark** [comment]
FWIW, The WASI build without LTO (which is used with YoWASP but not in the script I gave you) should be fairly lightweight.

**Comment by mmicko** [comment]
Sure. Will take care of it. @whitequark thanks for the script

**Pull request merged**
