### PR TITLE
Add codeowners file

### PR DESCRIPTION
**Pull request by nakengelhardt**
No ownership implied; on a voluntary basis, add yourself to this file to have github request a review from you when a file of interest is changed. You can add commits to this PR, or leave a comment here or on slack with lines you'd like me to add.

We also write down who was responsible for major external contributions, but anyone without write access will not automatically get notified by github if I understand correctly. It's still a convenient place to keep this information.

### CODE REVIEW

**Comment by ZirconiumX** [comment]
> anyone without write access will not automatically get notified by github if I understand correctly.

It's a little annoying that I won't get pinged, but could you add `techlibs/intel_alm/* @ZirconiumX` (presumably as external contributor)?

**Comment by whitequark** [comment]
It's possible to set things up so that external contributors *do* get pinged with GitHub actions.

**Comment by nakengelhardt** [comment]
Oh nice. How does that work? Will that also pull the info from the codeowners file (in which case we'd want to be more careful about asking first before adding people) or do you have to set it up separately?

**Comment by whitequark** [comment]
It's done by arbitrary code we can write, so basically whichever functionality you want is doable. Take a look at what [wasmtime does](https://github.com/bytecodealliance/wasmtime/tree/master/.github): they have auto-addition of labels, and then auto-subscription to labels, chained together.

**Comment by nakengelhardt** [comment]
OK, so after testing a little, the precise behavior if a line lists a code owner that does not have write permissions is that the review request does not get sent automatically, but the line *does* override (and hence potentially disable) previous lines.

**Comment by nakengelhardt** [comment]
Let's squash merge this PR at the end to not have so many redundant commits.

**Comment by nakengelhardt** [comment]
This is currently not of much practical relevance, but putting `*` at the end of the path [explicitly excludes any subdirectories](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#example-of-a-codeowners-file), did you mean to do that?

@whitequark  For `rpc` and `cxxrtl` there aren't any subdirectories yet, but would you want to be notified if someone adds one?

@ZirconiumX For `intel_alm` it won't be automatic anyway but I took the liberty of removing the `*` since you wrote the contents of the subdirectory `common/` as well...

**Comment by ZirconiumX** [comment]
That's fine. In practice I'm the only person working on and using intel_alm
presently anyway, so I expect changes to the codebase there to be rare in
practice.

**Comment by whitequark** [comment]
> @whitequark For `rpc` and `cxxrtl` there aren't any subdirectories yet, but would you want to be notified if someone adds one?

Yep, I didn't read the syntax of the codeowners file very carefully. Let's ditch `*`.

**Comment by nakengelhardt** [comment]
OK, done.

**Pull request merged**
