### PR TITLE
cxxrtl: Convert to Mem helpers.

### PR DESCRIPTION
**Pull request by mwkmwkmwk**
This *only* does conversion, but doesn't add any new functionality —
support for memory read port init/reset is still upcoming.

### CODE REVIEW

**Comment by mwkmwkmwk** [comment]
TODOs (may or may not end up as separate PRs):

- add initial value support for read ports
- add reset support for read ports
- handle memory writes in processes

Other upcoming changes:

- support for meminit_v2 (memory initialization with mask)
- support for per-port transparency masks (blocked on model changes)

**Comment by whitequark** [comment]
Really like this approach!

**Comment by mwkmwkmwk** [comment]
I think it's ready for review now; some notes:

- every read port is a distinct node (to avoid creating false dependencies between one port's address and another's data), but all write ports of a single memory are a single node (I wrote it this way to make it easier to handle priority, without noticing that `update` is already fully capable of dealing with this; we could change it if necessary)
- port/memory attributes aren't printed right now, which is a minor regression; it may be a good idea to convert `kernel/mem.h` classes to inherit from `AttrObject` so that we can just `dump_attrs` them

**Comment by mwkmwkmwk** [comment]
Rebased with minor fix: processes with a memory write are now always inserted into `live_nodes`

**Comment by whitequark** [comment]
> * but all write ports of a single memory are a single node (I wrote it this way to make it easier to handle priority, without noticing that `update` is already fully capable of dealing with this; we could change it if necessary)

This is potentially _a lot better_ than the approach with `update` because sorting the queue vector takes a non-trivial amount of time in benchmarking. Since I think the concept of priority only really makes sense within a netlist (and not between co-simulating entities), we could ditch that entirely and have `Memory::update` do last-write-wins.

**Comment by whitequark** [comment]
> * port/memory attributes aren't printed right now, which is a minor regression; it may be a good idea to convert `kernel/mem.h` classes to inherit from `AttrObject` so that we can just `dump_attrs` them



> * port/memory attributes aren't printed right now, which is a minor regression; it may be a good idea to convert `kernel/mem.h` classes to inherit from `AttrObject` so that we can just `dump_attrs` them

Would that be hard to do? It seems like one of those small things that otherwise easily fall through the cracks. (Not something I'd hold up the PR on, of course.)

**Comment by mwkmwkmwk** [comment]
> > * port/memory attributes aren't printed right now, which is a minor regression; it may be a good idea to convert `kernel/mem.h` classes to inherit from `AttrObject` so that we can just `dump_attrs` them
> 
> Would that be hard to do? It seems like one of those small things that otherwise easily fall through the cracks. (Not something I'd hold up the PR on, of course.)

Don't think so; I'll have a shot at it tomorrow, probably.

**Comment by mwkmwkmwk** [comment]
Done, turns out it was pretty trivial.

**Review by whitequark — APPROVED** [review]
LGTM

**Comment by mwkmwkmwk** [comment]
Fixing one more bug noticed in own review: we need to take into account memory writes from processes as well when deciding whether to emit `commit` (ie. `writable_memories` is back)

**Comment by mwkmwkmwk** [comment]
The macOS builder seems stuck, trying a dummy push-force to kick it...

**Pull request merged**
