### PR TITLE
Add additional cells sim models for core 7-series primitives.

### PR DESCRIPTION
**Pull request by litghost**
- Adds some parameters to IBUF, OBUF primitive
- Add more general clock primitives, the BUFGCTRL and BUFHCE primitives
- Add LUT6_2 primitive

### CODE REVIEW

**Comment by litghost** [comment]
There is a copy/paste error in the LUT6_2, fix incoming shortly.

**Comment by litghost** [comment]
> Can you remove the entries of the newly inserted cells from:
> 
> [yosys/techlibs/xilinx/cells_xtra.sh](https://github.com/YosysHQ/yosys/blob/e107ccdde82247e28c9c994240e4d4bf694f673f/techlibs/xilinx/cells_xtra.sh#L31)
> 
> Line 31 in [e107ccd](/YosysHQ/yosys/commit/e107ccdde82247e28c9c994240e4d4bf694f673f)
> 
>  xtract_cell_decl BUFGCTRL 
> [yosys/techlibs/xilinx/cells_xtra.v](https://github.com/YosysHQ/yosys/blob/e107ccdde82247e28c9c994240e4d4bf694f673f/techlibs/xilinx/cells_xtra.v#L33)
> 
> Line 33 in [e107ccd](/YosysHQ/yosys/commit/e107ccdde82247e28c9c994240e4d4bf694f673f)
> 
>  module BUFGCTRL (...); 
> So that they aren't duplicated?

Sure, done.

**Comment by eddiehung** [comment]
Thanks! Looks you missed one though:

https://github.com/litghost/yosys/blob/640573d5aec1ea3ab056ff5a2f8fb35787e9f0e6/techlibs/xilinx/cells_xtra.v#L2391

**Comment by litghost** [comment]
> Thanks! Looks you missed one though:
> 
> https://github.com/litghost/yosys/blob/640573d5aec1ea3ab056ff5a2f8fb35787e9f0e6/techlibs/xilinx/cells_xtra.v#L2391

Opps, fixed

**Comment by eddiehung** [comment]
Great! Will merge once CI comes back clean.

**Pull request merged**
