### PR TITLE
Fix different synth results between with and without debug output "-g"

### LINKED ISSUE #1178: Different results with and without debug flag "-g"
## Steps to reproduce the issue

```
./yosys -p "synth_xilinx -abc9" picorv32.v &> nodebug.out
./yosys -p "synth_xilinx -abc9" picorv32.v -g &> debug.out
diff debug.out nodebug.out -y
```
gives
```
=== design hierarchy ===                                        === design hierarchy ===

   picorv32_wb                       1                             picorv32_wb                       1
     $paramod$4d2dfdcc1db1a7362453fb449ccdda75bb1b39f9\picorv        $paramod$4d2dfdcc1db1a7362453fb449ccdda75bb1b39f9\picorv

   Number of wires:               1175                        |    Number of wires:               1170
   Number of wire bits:           4107                        |    Number of wire bits:           4102
   Number of public wires:         181                             Number of public wires:         181
   Number of public wire bits:    1760                             Number of public wire bits:    1760
   Number of memories:               0                             Number of memories:               0
   Number of memory bits:            0                             Number of memory bits:            0
   Number of processes:              0                             Number of processes:              0
   Number of cells:               2351                        |    Number of cells:               2346
     CARRY4                        101                               CARRY4                        101
     FDRE                          680                               FDRE                          680
     LUT1                            9                               LUT1                            9
     LUT2                          702                        |      LUT2                          703
     LUT3                          110                        |      LUT3                           99
     LUT4                          138                        |      LUT4                          132
     LUT5                          439                        |      LUT5                          443
     LUT6                          107                        |      LUT6                          115
     MUXF7                           1                        <
     RAM32X1D                       64                               RAM32X1D                       64

   Estimated number of LCs:       1021                        |    Estimated number of LCs:       1025
```

## Expected behavior

No divergence.

## Actual behavior

Divergence.

### PR DESCRIPTION
**Pull request by eddiehung**
Fixes #1178

### CODE REVIEW

**Comment by eddiehung** [comment]
@cliffordwolf It seems that with your commits I no longer need 1122a2e. I tried reverting it and still got the same synth result.

**Comment by eddiehung** [comment]
Okay that also brings up the question of whether 0e6c830 is also needed. I tried it locally and got the same synth result too.

**Comment by cliffordwolf** [comment]
Tbh, I don't really understand why 1122a2e made a difference in the first place. ;)

Yes, I think 0e6c830 and `log_checkpoint()` shouldn't be needed when we have 44fd459.

**Comment by eddiehung** [comment]
Okay I reverted those two commits. Will merge when CI goes green. Thanks for taking over!

**Pull request merged**
