### PR TITLE
[WIP] Add "whitebox" attribute, add "read_verilog -wb"

### PR DESCRIPTION
**Pull request by cliffordwolf**

### CODE REVIEW

**Comment by eddiehung** [comment]
Made two small changes -- one for `flatten -wb` and another for disabling the contents of blackboxes (black + white) from being written out in `write_json`

**Comment by eddiehung** [comment]
Another potential talking point: `techmap` will reach into whiteboxes (which is actually useful for my use case)

**Comment by daveshah1** [comment]
The problem seems to be the equivalence check failing because it is skipping the content of whitebox cells - it is running 'read_verilog' without -lib so previously would have seen the content of this cells. The equivalence checking and SAT stuff should probably be looking inside whitebox cells.

**Comment by cliffordwolf** [comment]
> Another potential talking point: techmap will reach into whiteboxes (which is actually useful for my use case)

Yeah, that's a bug. I've now fixed this and added a `wbflip` command that can be used to switch back and forth between synthesis/logic optimization for whiteboxes and the actual design.

**Comment by cliffordwolf** [comment]
> The equivalence checking and SAT stuff should probably be looking inside whitebox cells.

f3ad8d6 should do that now

**Comment by eddiehung** [comment]
Previous `SB_CARRY` issue now resolved.

**Pull request merged**
