### PR TITLE
Fix CXX variables in Makefile

### PR DESCRIPTION
**Pull request by RCoeurjoly**
Thanks to the comment by @KrystalDelusion in https://github.com/YosysHQ/yosys/issues/4244#issuecomment-1975402037, the solution was found.

This PR fixes https://github.com/YosysHQ/yosys/issues/4244.

### CODE REVIEW

**Comment by RCoeurjoly** [comment]
the emcc pipeline fails, it seems to be related to the CXX variable

**Comment by KrystalDelusion** [comment]
TIL make automatically provides a default value of `CXX = g++`, which can be seen as it is g++ returning the error.  I suspect `make config-clang; make` would also run g++ in this case despite the implication of using the clang config; which (in hindsight) is probably why this was setup the way it was.  Rather than changing the the CXX assignments, it might make more sense to assign `CONFIG=none` by default and leave config-gcc/config-clang etc to override as previously intended.

@RCoeurjoly can you check if #4270 also fixes your issue?  You'll want to delete `Makefile.conf` first and then go straight to `make` (no call to `make config-clang`)

**Comment by RCoeurjoly** [comment]
> TIL make automatically provides a default value of `CXX = g++`, which can be seen as it is g++ returning the error. I suspect `make config-clang; make` would also run g++ in this case despite the implication of using the clang config; which (in hindsight) is probably why this was setup the way it was. Rather than changing the the CXX assignments, it might make more sense to assign `CONFIG=none` by default and leave config-gcc/config-clang etc to override as previously intended.
> 
> @RCoeurjoly can you check if #4270 also fixes your issue? You'll want to delete `Makefile.conf` first and then go straight to `make` (no call to `make config-clang`)

I confirm that PR 4270 fixes this issue.

**Comment by KrystalDelusion** [comment]
Awesome.  I'll close this one in favour of that then.

**Pull request closed without merging**
