### PR TITLE
Add "write_edif -lsbidx"

### PR DESCRIPTION
**Pull request by cliffordwolf**

### CODE REVIEW

**Comment by eddiehung** [comment]
For future lifeforms, which tool(s) have you found require this?

**Comment by nakengelhardt** [comment]
@eddiehung: None; this is an incomplete workaround/bug-finding session for trying to export an edif with a blackbox module whose port widths depend on a parameter. Attempting this found several bugs:

- edif doesn't support variable-width signals, but the cell is only declared once, so the instance widths don't match the declaration width
- consequently, if the instance width is larger, the connections end up using negative indices (this is what -lsbidx works around, it reverses the connection direction so at least they are positive, but of course this results in the bits being connected in the wrong order if you instantiate it in a design in vivado - I was doing out-of-context synthesis to look at area and timing, so this didn't matter in my case)
- the cell declaration takes the default parameter width but the wire name takes the width from a random instance, so they don't match (this is what the second commit is about)
- yosys can't distinguish between a port "a" and a port "a[0:0]" and defaults to the former; but these require different syntax to connect to in edif, so the edif ends up broken if one of the instances parametrizes a port to a width of 1.

This draft PR doesn't fix these issues, it's just some code from Clifford that I used to continue tracking down the bugs. An actual fix will probably need to tie into hierarchy to figure out how port widths are affected by parameter settings, and export a separate blackbox cell for each parameter set.

**Comment by nakengelhardt** [comment]
Despite arising out of a different background, this would actually be a partial fix for issue (enhancement) #568. It adds point 1 of the options laid out [here](https://github.com/YosysHQ/yosys/pull/830#issuecomment-468453251). Leaving it open for now so it can be completed later.

**Comment by peterzieba** [comment]
I'm very curious about using the ATF150x CPLDs with yosys. What would be needed for these changes to be merged? I believe this might be the only thing necessary to generated EDIF for the Atmel fitter.

**Pull request merged**
