### PR TITLE
OS X related Makefile fixes.

### PR DESCRIPTION
**Pull request by Kmanfi**
Cleaned my OS X Makefile and put needed if(Darwin..) #1029 fix is also included in this.
This PR fixes also  -DWITH_PYTHON mentioned in #1027

### CODE REVIEW

**Comment by cliffordwolf** [comment]
I definitely approve of using `$(shell .. )` in PYTHON_PREFIX, however, it would make sense to put the entire block of `PYTHON_* := ` assignments in an `ifeq ($(ENABLE_PYOSYS),1)` block so that those shell commands aren't executed when `ENABLE_PYOSYS` is not active.

cc @btut @mmicko please comment on the pyosys and MacOS aspects of the PR respectively.

**Comment by mmicko** [comment]
Can confirm that without change it does not find boost python at all, and that with changes it compiles and runs fine on macOS.

**Comment by thasti** [comment]
From what I can see, this MR broke building yosys+libyosys+pyosys with having 
```
ENABLE_LIBYOSYS=1
ENABLE_PYOSYS=1
```
in Makefile.conf (on Linux). Any chance of having a second look?


Currently failing with:
```
[Makefile.conf] CONFIG := gcc
[Makefile.conf] ENABLE_LIBYOSYS=1
[Makefile.conf] ENABLE_PYOSYS=1
/bin/sh: -config: command not found
/bin/sh: -config: command not found
/bin/sh: -config: command not found
/bin/sh: -config: command not found
```

**Comment by mmicko** [comment]
Issue here is that ENABLE_PYOSYS is checked before .conf is included. In order to work fine, block setting variables needs to be moved below include Makefile.conf, but then overriding those variables (PYTHON_EXECUTABLE for example) could be possible only from command line not from conf as well.

**Comment by cliffordwolf** [comment]
I think the solution is maybe to include `Makefile.conf` multiple times? Idk..

**Comment by mmicko** [comment]
That will work, anyway it can be only loaded one more time inside ENABLE_PYOSYS block after all variables are assigned, that could be cleanest way of doing it

**Comment by cliffordwolf** [comment]
Including `Makefile.conf` multiple times may also be a good solution for #478.

**Comment by mmicko** [comment]
Option is also to include Makefile.conf at very beginning of file and then do conditional assignment (?=) for all variables, that would changed them only if they are not yet assigned. We can discuss this offline.

**Comment by thasti** [comment]
Thanks for fixing this so quickly, my builds are back to normal!

**Pull request merged**
