### PR TITLE
Add several new formatting features used by Amaranth to translate Python format strings

### PR DESCRIPTION
**Pull request by whitequark**
This is a work-in-progress PR at the moment.
- [x] `H` format type (uppercase hex digits)
- [x] `c` format type (Unicode code point emitted as UTF-8)
- [x] `=` justification (align right, but after the padding)
- [x] arbitrary fill character
- [x] ` ` sign mode (either `-` or ` `, as opposed to either `-` or `+`)
- [x] `_` option (insert an underscore between each 3 decimal, 4 binary/octal/hex digits)
- [x] `#` option (insert `0x`/`0o`/`0b` after sign and before padding)
- [x] signed hex numbers
- [x] padding interacts poorly with base
- [x] consider combination of `0` padding and `_`
- [x] test integration with Amaranth

### CODE REVIEW

**Comment by whitequark** [comment]
@mmicko I need to have these in the next Yosys release to meet the current Amaranth release schedule. The PR should be done by the 1st or very shortly after.

**Comment by povik** [comment]
This looks like it overlaps or supersedes #4192.

**Comment by whitequark** [comment]
@povik I *think* there's actually no overlap? Note `VerilogFmtArg` vs `FmtPart`.

**Comment by povik** [comment]
Right you are

**Pull request merged**
