### PR TITLE
Allow constant function calls in constant function arguments

### PR DESCRIPTION
**Pull request by zachjs**

### CODE REVIEW

**Review by whitequark — COMMENTED** [review]
Can you explain how this change works? It is not clear to me from the context what actually happnens here.

**Comment by zachjs** [comment]
`has_const_only_constructs` is used later on in `simplify` to detect whether an `AST_FCALL` needs to be evaluated during elaboration. However, the arguments of any `AST_FCALL` are `simplify`-ed earlier on, at the site where I made my changes. This earlier simplification previously turned the function arguments into wires. With this change, if the `AST_FCALL` needs to be evaluated during elaboration, then the arguments themselves are evaluated as constants, rather than being turned into wires.

**Review by whitequark — APPROVED** [review]
LGTM

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
