### PR TITLE
equiv_opt: new command, for verifying optimization passes

### PR DESCRIPTION
**Pull request by whitequark**
When writing optimization passes I heavily rely on `equiv` commands to verify correctness. I have a few scripts for that locally, but Yosys scripts are not very flexible, and I feel this is in general a very useful shortcut command to have. This is also quite useful for tests.

### CODE REVIEW

**Comment by mithro** [comment]
Yes please! This is awesome.

**Comment by whitequark** [comment]
> What do you prefer for easy-to fix indenting stuff like this: Shall I just merge it and fix indenting ontop of it, potentially (but unlikely) causing merge conflicts don't the road for you, or should I complain in a change request like this and let you fix it, potentially causing a bit of overhead work?

Whatever results in less work for you. I am (unfortunately) proficient with Git so any merge conflicts upstream add maybe a few seconds required to type the right rebase command. Not an issue for me at all.

**Comment by cliffordwolf** [comment]
In that case I'll simply merge and then commit indenting fixes ontop, and post a note like this one:

Merged with indenting fixes, see f53e19c.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
