### PR TITLE
Format files in yosys/passes/techmap

### PR DESCRIPTION
**Pull request by rmlarsen**
The files were formatted in accordance with yosys/.clang-format using the command:

 % clang-format -i -style=file:./.clang-format passes/techmap/*.{cc,h}

### CODE REVIEW

**Review by whitequark — CHANGES_REQUESTED** [review]
My usual questions with these changes are:
- How do we keep the code formatted?
- What happens to `git blame`?

Especially the second.

Absent a satisfactory answer I wouldn't want to see it happen.

**Comment by Ravenslofty** [comment]
(There are also my personal opinions about enforcing formatting being something of a barrier to entry (nevermind an accessibility issue to some), and heaven knows that newcomers to Yosys are few enough already...)

**Comment by whitequark** [comment]
> There are also my personal opinions about enforcing formatting being something of a barrier to entry

I agree! Failing CI because clang-format failed is so absurdly disrespectful to your contributors that unless I *really* want to get my commit in I would just not bother probably.

**Comment by rmlarsen** [comment]
Oh, I agree! I just assumed that the presence of the `.clang-format`  file was an indicator that you put some value on enforcing a unified code formatting (as much as I find the existing formatting with 8 space tabs bizarre and ugly.)

If that's not the case, I'm more than happy to back out formatting changes to all my PRs.

**Comment by rmlarsen** [comment]
BTW: There are ways to tell git blame to ignore certain PRs. I believe this is supported by github.( It is unfortunatelt not supported by gitlab where we host Eigen  :-( .) See https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt

I agree that this change by itself does not make sense. It seems that the Yosys maintainers need to make a decision regarding the enforcement of formatting.

**Pull request closed without merging**
