### PR TITLE
Add DLLDELD

### PR DESCRIPTION
**Pull request by ECP5-PCIe**

### CODE REVIEW

**Review by mwkmwkmwk — APPROVED** [review]

**Comment by ECP5-PCIe** [comment]
Somehow I get a "ERROR: cell type 'DLLDELD' is unsupported (instantiated as 'U$$0.U$$0')" in NextPNR

**Comment by gatecat** [comment]
Yeah, it's not supported. If you have a use case I'm happy to work on adding support (hopefully tomorrow), it shouldn't take long.

**Comment by ECP5-PCIe** [comment]
Yes, that would be nice, since I want to use it to delay signals over a larger range than a DelayF can

**Comment by gatecat** [comment]
Would you be able to point me to some code that's using it so I have a reference point to work with?

**Pull request merged**
