### PR TITLE
Update ABC to latest

### PR DESCRIPTION
**Pull request by mmicko**

### CODE REVIEW

**Comment by mmicko** [comment]
@jix If you could please check if this affects anything sby/eqy related

**Comment by whitequark** [comment]
@mmicko  This breaks the Wasm build: https://github.com/YoWASP/yosys/actions/runs/6166481665/job/16736046078

**Comment by mmicko** [comment]
@whitequark ah, sorry for that, not sure I will have time for a fix soon, but if you can provide patch it would be great

**Comment by whitequark** [comment]
@mmicko Can we revert until this is fixed?

**Comment by whitequark** [comment]
Actually that looks like an easy fix, patch incoming

**Pull request merged**
