### PR TITLE
Add WASI CI build

### PR DESCRIPTION
**Pull request by mmicko**
Added script from https://github.com/YosysHQ/yosys/pull/4045, was not able to reproduce a bug but it more looks like order of execution issue in passes/pmgen directory. Let see if this CI is happy.

### CODE REVIEW

**Review by whitequark — APPROVED** [review]
LGTM

**Comment by povik** [comment]
I am not that familiar with GitHub Actions but I wonder if splitting the SDK fetch from the other commands and putting it above the source checkout would cause GitHub to sometimes cache the environment with the unpacked SDK tree

**Comment by mmicko** [comment]
No caching enabled here so no issues. Spliting into multiple steps does not help since there is no reuse. Leaving this to  be decided on Mondays meeting.

**Comment by povik** [comment]
Well, I meant caching by the GitHub infrastructure itself, since it sees there are no variable inputs to the workflow up to the point of the source checkout. Though it's probably not that clever to deduce the link to the SDK hasn't changed content

**Comment by whitequark** [comment]
> Well, I meant caching by the GitHub infrastructure itself, since it sees there are no variable inputs to the workflow up to the point of the source checkout. Though it's probably not that clever to deduce the link to the SDK hasn't changed content

GitHub does no such thing. We could make it cache explicitly but there's no point since the SDK is downloaded from GitHub's infrastructure in the first place. There would be no meaningful difference in speed, it would just waste some space.

**Pull request merged**
